### ISSUE TITLE
NameError: name 'exit' is not defined

### ISSUE THREAD

**Issue by dymodi** [ToonWeyens/pylgrim#4]
Hi there, when I use the ESPPRC lib, a strange error is as follows:
`/usr/local/lib/python2.7/site-packages/pylgrim/ESPPRC.py in prune_graph(G, source, target, max_res, res_name)
     49         if target not in lengths_source:
     50             logger.error('target not reachable for resource {}'.format(res))
---> 51             exit()
     52 
     53         logger.debug('Calculate feasible paths to target for resource {}'.format(res))

NameError: name 'exit' is not defined`

I checked and found that this post may helps:
https://stackoverflow.com/questions/45066518/nameerror-name-exit-is-not-defined
but I am not sure whether this problem happens in your test.

Best,

**Comment by ToonWeyens** [comment]
Hi @dymodi, this is an error indeed. Thank you for first trying to fix it!

So, it basically means that the program wants to shut down because the target is not reachable, but that the proper library is not loaded.  

If you clone the newest newest commit from git (b099ad0474d10fede07f5cea480695c88cb3f07e) through

    git clone https://github.com/ToonWeyens/pylgrim.git

this should be fixed.

Also, I would recommend you to use python 3. Python 2 should only be used for legacy applications.

Now to the source of your error: You're trying to use ESPPRC for a graph where it is impossible to get from `source` to `target` with the resource costs specified. Have you checked this?

**Comment by dymodi** [comment]
Hi @ToonWeyens thanks for the prompt reply, also thanks for the advice. 
I will add a connection check in my code before calling ESPPRC.
